rois:
  - filter_type: 0
    roi_type: 0
    index: -5
    anchors:
      -
        - 99.2849
        - 14.41191
        - 0
      -
        - 64.68596
        - 7.45987
        - 0
      -
        - 36.15834
        - 1.520679
        - 0
      -
        - -5.039024
        - -5.935198
        - 0
      -
        - -19.10857
        - -8.901402
        - 0
      -
        - -51.17375
        - -12.57038
        - 0
      -
        - -44.55402
        - -28.13079
        - 0
      -
        - -28.3467
        - -28.88431
        - 0
      -
        - -9.397354
        - -60.55322
        - 0
      -
        - 3.436485
        - -53.59243
        - 0
      -
        - 1.36557
        - -38.8595
        - 0
      -
        - 4.058884
        - -29.87332
        - 0
      -
        - 12.10523
        - -23.25519
        - 0
      -
        - 18.27216
        - -20.29738
        - 0
      -
        - 17.99731
        - -19.3953
        - 0
      -
        - 67.31337
        - -9.465752
        - 0
      -
        - 88.87435
        - -5.202808
        - 0
      -
        - 99.83555
        - -2.290861
        - 0
      -
        - 99.00844
        - 22.82805
        - 0
  - roi_type: 0
    filter_type: 0
    index: 6
    anchors:
      -
        - 97.60097
        - 22.57253
        - 0
      -
        - 81.5388
        - 18.94558
        - 0
      -
        - 68.19684
        - 15.57771
        - 0
      -
        - 35.42484
        - 9.48963
        - 0
      -
        - -3.694304
        - 2.753886
        - 0
      -
        - -22.34715
        - -0.6139871
        - 0
      -
        - -53.0466
        - -4.499999
        - 0
      -
        - -66.5181
        - 26.97667
        - 0
      -
        - -74.93778
        - 45.2409
        - 0
      -
        - -55.63728
        - 54.43779
        - 0
      -
        - -53.17614
        - 45.2409
        - 0
      -
        - -50.19686
        - 38.50516
        - 0
      -
        - -43.59065
        - 32.02847
        - 0
      -
        - -38.79791
        - 29.17874
        - 0
      -
        - -35.04143
        - 27.1062
        - 0
      -
        - -26.23315
        - 22.70206
        - 0
      -
        - -12.37306
        - 20.88859
        - 0
      -
        - -7.83938
        - 21.40672
        - 0
      -
        - -7.709847
        - 20.75905
        - 0
      -
        - 32.31603
        - 27.62433
        - 0
      -
        - 57.96368
        - 31.63988
        - 0
      -
        - 66.9015
        - 32.93521
        - 0
      -
        - 81.15019
        - 33.84194
        - 0
      -
        - 89.82894
        - 35.26682
        - 0
      -
        - 98.37817
        - 36.95075
        - 0
  - anchors:
      -
        - -151.6212
        - -3.053887
        - 0
      -
        - -89.69897
        - 6.987555
        - 0
      -
        - -76.50729
        - 9.645585
        - 0
      -
        - -73.45547
        - -7.779272
        - 0
      -
        - -147.4865
        - -19.19895
        - 0
    index: -3
    roi_type: 0
    filter_type: 0