common:
    device_id: 1          #
messages:
    objects: true    # true if need send, otherwise false
    attention_objects: false
    object_supplement: false
    freespaces: true 
    curbs: false  
    lanes: false
    non_ground_indices: false
    ground_indices: false 
    background_indices: false 
    pointcloud: false
    pose: false 
sample:
    sample_pc: false              # Enable Sample Non-Object PointCloud 
    method: "RATIO_NON_OBJECT"    # "RATIO_NON_OBJECT"
    sampleScale: 0.50             # Sample Scale <= 1.0
    sample_obj: false             # Enable Sample Object Indices 
    sampleObjectIdxCnt: 100       # Sample Object Max Leave Indices Size 
udp:
    socket_buffer_size: 4194304   # bytes, default is 4MB 
    max_msg_size: 7148            # bytes, default is 10KB 
    socket_buffer_cell: 1024      #  
    socket_remote_ip: 10.10.9.192 # 10.10.8.150 # 10.10.8.36  #
    socket_remote_port: 60081     #
    max_rev_time_ms: 90           #
v2r: 
    common: 
        method: "TCP_SERVER"      # "UDP_SENDER" / "TCP_CLIENT" / "TCP_SERVER"
        max_msg_size: 7148        # 
        socket_buffer_cell: 16    #  
    socket: 
        socket_ip: 10.10.8.150     # remote ip   / 0.0.0.0 
        socket_port: 60081         # remote port / listen port     
        socket_buffer_size: 4194304 
    heading: 
        velocity_heading_th: 0.5      # m/s 
        acceleration_heading_th: 0.05 # m/s^2  
        acceleration_valid: false     # 
ros:
    frame_id: percept_frame_id    # ros frame_id
    ros_topic: percept_topic      #  
    snd_nodename: percept_snd     # not use 
    rcv_nodename: percept_rcv     # not use 
websocket: 
    common: 
        socket_listen_port: 8081       # 
    enables: 
        object: 
            cube: true 
            box: false 
            polygon: false 
            polyhedral: false 
            tracking_point: false 
            trajectory: false 
            velocity_dir: true 
            box_info: true 
            label_info: true
            track_info: true 
            gps_info: true 
        attention_object: 
            polygon: false 
            polyhedral: true 
    objects:                       # Support Object Type and Color Attribution
        object00:  
            type: unknown
            typeid: 0  
            color: [153, 128, 153, 76]
        object01:    
            type: pedestrian 
            typeid: 1 
            color: [255, 255, 0, 76]
        object02: 
            type: bikelist
            typeid: 2 
            color: [0, 255, 0, 76]
        object03:  
            type: car 
            typeid: 3 
            color: [0, 255, 255, 76]
        object04: 
            type: truck
            typeid: 4 
            color: [0, 255, 255, 76]
        object05: 
            type: ultra-track
            typeid: 5  
            color: [0, 255, 255, 76]
    attention_objects: 
        color: [255, 0, 255, 255]        # attention_object颜色
    object_attachs: 
        track_points: 
            color: [0, 255, 0, 128] 
            attach_object: false          # 不关联Object颜色
        trajectory: 
            color: [255, 0, 0, 128]
            attach_object: true          # 关联物体颜色
        label_text: 
            color: [255, 255, 255, 255]
            attach_object: false        # 白色，不关联Object颜色
        track_text: 
            color: [255, 255, 255, 255] 
            attach_object: false        # 白色，不关联Object颜色
        box_text: 
            color: [255, 255, 255, 255] 
            attach_object: false          # 白色，不关联Object颜色
        gps_text: 
            color: [255, 255, 255, 255] 
            attach_object: false          # 白色，不关联Object颜色
        velocity_dir: 
            color: [0, 255, 0, 255]
            attach_object: false          # 不关联Object颜色
        acc_dir: 
            color: [0, 255, 0, 255]
            attach_object: false          # 不关联Object颜色
    lanes: 
        color: [0, 255, 0, 255] # [56, 56, 56, 255]
    curbs: 
        color: [255, 0, 0, 255] # [56, 56, 56, 255]
    freespaces: 
        color: [77, 77, 77, 255]
    transform: 
        matrix: [1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]
    lidar_grids: 
        grid_circle_ranges: [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 150, 200, 250]                            # circle grid 的半径
        grid_circle_segments: [150, 150, 150, 150, 250, 250, 250, 250, 400, 400, 400, 400, 400]                 # 
        grid_circle_bolds: [false, false, false, false, true, false, false, false, false, true, false, false, false]  # = true表示对应的circle需要加粗, No Used
        grid_circle_color: [160, 160, 164, 255]
    color_map: 
        color_map_enable: false 
        color_map_type: "hsv"            # "autumn"/"bone"/"jet"/"winter"/"rainbow"/"ocean"/"summer"/"spring"/"cool"/"hsv"/"pink"/"hot"/"parula"  
        color_map_factors: ["intensity"] # "x" / "y" / "z" / "intensity"
        color_map_lows: [0]              # 
        color_map_highs: [128]           # 
        color_map_alphas: [1.0]          # 
        color_map_invert: false          # 
        color_map_label: false           # always is false now 
        default_color: [230, 230, 230, 255]
    map_origin: 
        lat: 0
        lon: 0
        alt: 0 
    fill_images: 
        camera2: "/fill_images/robo_log2.png"
        camera3: "/fill_images/robo_log3.png"


