preprocess_config:
  range_filter:
    enable: true
    range:
      xmin: -3.0
      xmax: 3.0
      ymin: -1.0
      ymax: 1.0
  enable_roi: false
deep_detection_config:
  enable: True
  stratety: "taurus" #"polaris","libra_efficient","libra","leo","taurus"
  bbox_mode: "reg_box"  #"tight","reg_ang","reg_box"
  show_affinity_info: true
  preprocess_affinity_id: 0
  infer_affinity_id: 1
  postprocess_affinity_id: 2
  use_default_model_config: true
  polaris_deep_detection_config:
    use_cuda_acc: true
    detect_range:
      xmin: -80.
      xmax: 80.
      ymin: -80.
      ymax: 80.
      zmin: -3.
      zmax: 3.5
    regress_height_thd: 0.5
    density_base: 1.
    enable_intensity_normalize: false
    nms_thres: 0.5
    regression_box_confidence_thre: 0.0
    enable_fp_16: false
    max_workspace: 30
    min_pts_num: 3
    ground_height_thd: 1.2
    ground_h_error_thd: 0.2
  virgo_deep_detection_config:
    detect_range:
      xmin: 0.
      xmax: 192.
      ymin: -60.
      ymax: 60.
      zmin: -3.
      zmax: 3.5.
    regress_height_thd: 0.5
    nms_thres: 0.1
    regression_box_confidence_thre: 0.0
    enable_fp_16: false
    max_workspace: 30
    min_pts_num: 3
    ground_height_thd: 1.2
    ground_h_error_thd: 0.2
  taurus_deep_detection_config:
    use_cuda_acc: True
    detect_range:
      xmin: -80.
      xmax: 80.
      ymin: -80.
      ymax: 80.
      zmin: -3.
      zmax: 5.
    regress_height_thd: 0.5
    regression_box_confidence_thre: 0.0
    nms_thres: 0.3
    density_base: 1.
    enable_intensity_normalize: false
    enable_fp_16: false
    max_workspace: 30
    min_pts_num: 3
    ground_height_thd: 1.0
    ground_h_error_thd: 0.2
  libra_deep_detection_config:
    lidar_height: 0.6
    front_view_config:
      rows: 64
      cols: 512
      min_height: -5.0
      max_height: 5.0
      min_vert_angle: -12.5
      max_vert_angle: 12.5
      min_horizon_angle: -60
      max_horizon_angle: 60
    range: 180
    min_pts_num: 3
    delta_x: 0.5
    delta_y: 0.5
    use_intensity: true
    enable_intensity_normalize: false
    enable_fp_16: false
    max_workspace: 30
    ground_x_range: 30.0
    ground_y_range: 20.0
    ground_fv_max_height: 0.2
    ground_bev_max_height: 0.4
    ground_bev_unit_size: 0.5
  leo_deep_detection_config:
    lidar_height: 0.6
    front_view_config:
      rows: 64
      cols: 512
      min_height: -5.0
      max_height: 5.0
      min_vert_angle: -12.5
      max_vert_angle: 12.5
      min_horizon_angle: -60
      max_horizon_angle: 60
    range: 180
    min_pts_num: 3
    delta_x: 0.5
    delta_y: 0.5
    use_intensity: true
    enable_intensity_normalize: false
    enable_fp_16: false
    max_workspace: 30
    ground_x_range: 30.0
    ground_y_range: 20.0
    ground_fv_max_height: 0.2
    ground_bev_max_height: 0.4
    ground_bev_unit_size: 0.5
    ## leo threshes
    dist_thresh: 0.5
    proposal_size_thresh: 1
    proposal_ratio_thresh: 0.0f
    uncluster_thresh: 0
    seed_thresh: 0.0
ground_filter_config:
  enable: true
  strategy: "bev"
  bev_config:
    range:
      xmin: -50.
      xmax: 50.
      ymin: -50.
      ymax: 50.
      zmin: -3.
      zmax: 5.
    unit_ang_angle: 1.
    unit_size: 0.5
    max_ang_angle: 5.
    max_herr: 0.2
    max_h: 0.5
segmentor_config:
  enable: false
  strategy: "bev"
  bev_config:
    bird_view_config:
      range:
        xmin: -50.
        xmax: 50.
        ymin: -50.
        ymax: 50.
        zmin: -1.
        zmax: 2.
      unit_size: 0.2
    seg_dilate: false
    seg_scan_x: 0.5
    seg_scan_y: 0.5
    seg_min_pts: 3
  box_classify:
      enable: false
road_detection_config:
  enable: true
  strategy: "roadlink"
  roadlink_config:
    lane_detection:
      enable: true
      frame_fusion: false
      tracking: true
      auto_align: false
      unit_size: 0.2
      x_range: 30.0
      y_range: 20.0
      lane_width: 3.2

